### ISSUE TITLE
v1.2.5 Errors persist

### ISSUE THREAD

**Issue by SecretSquirrel77** [AmazingVanish/apsj4mej#3] opened 2022-02-08 01:57 UTC
All modules with the exception of Stylish Journal and Monk's Enhanced Journal disabled. 
Foundry V9, DnD 5e 1.5.7

BookInsanity.otf throws Err: 404
When closing the journal with the control panel open, the panel persists

![Capture](https://user-images.githubusercontent.com/77705375/152903263-f5df2098-1092-4258-bf1d-ffb8f9e869d1.PNG)

**Comment by SecretSquirrel77** [comment] 2022-02-08 01:58
If you are unable to replicate, then I don't know what else to say. Perhaps an issue on my end. Either way, best of luck going forward!

**Comment by AmazingVanish** [comment] 2022-02-08 02:05
Ah, ok I understand your persistence problem now. That I CAN reproduce. Hmm. I assume it's because TInyMCE is truncating the menu instead of wrapping it. I'll have to see if  I can fix that.

The font issue I can't reproduce though. I'm not seeing any errors in the console and the font works fine. Can you provide a screenshot of the font error for me? Not sure it will help, but I'm grasping at straws at this point.

**Comment by AmazingVanish** [comment] 2022-02-08 18:37
The persistence issue is fixed in version 1.3.0 which should release later today. I'm still at a loss over the BookInsanity font issue you're having.

**Comment by AmazingVanish** [comment] 2022-02-12 03:36
Closing due to lack of response

**Closed as completed by AmazingVanish** 2022-02-12 03:36 UTC
